/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package test
import smile.clustering.KMeans

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }

    val data = arrayOf(
    doubleArrayOf(1.0, 2.0, 3.0),
    doubleArrayOf(4.0, 5.0, 6.0),
    doubleArrayOf(7.0, 8.0, 9.0)
    )

    val k = 2.0
    val y = IntArray(data.size)
    val kmeans = KMeans(k, data, y)

}

fun main() {
    println(App().greeting)
    // println(App().kmeans)
}
